<?php
require_once __DIR__ . '/includes/helpers.php';
require_once __DIR__ . '/includes/market-instruments.php';
$siteName = get_site_name();
$pageTitle = $siteName . ' | AI Trading Signals & Live Markets';
$cryptoIds = array_values(array_filter(array_map(fn($m) => $m['coingecko_id'] ?? null, get_markets_by_category('crypto'))));
?>
<!DOCTYPE html>
<html class="dark" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta name="description" content="AI-powered trading signals and live market data for crypto, stocks, and forex on <?php echo htmlspecialchars($siteName); ?>."/>
<?php require_once __DIR__ . '/includes/marketing-head.php'; ?>
</head>
<body class="marketing-page font-body-md text-body-md overflow-x-hidden">
<?php $currentPage = 'trading_signals'; require_once __DIR__ . '/includes/marketing-header.php'; ?>

<section class="pt-28 pb-8 bg-surface-container-lowest border-b border-border-low">
<div class="max-w-[1440px] mx-auto px-4 md:px-margin-desktop">
<div class="flex flex-col md:flex-row md:items-end justify-between gap-4">
<div>
<div class="flex items-center gap-3 mb-3">
<h1 class="font-headline-md text-headline-md text-on-surface">AI-Powered Trading Signals</h1>
<div class="flex items-center gap-2 px-3 py-1 bg-red-500/10 rounded-full border border-red-500/20">
<div class="w-2 h-2 bg-red-500 rounded-full pulse-live"></div>
<span class="text-[10px] font-bold text-red-400 uppercase tracking-widest">Live</span>
</div>
</div>
<p class="text-on-secondary-container max-w-2xl text-body-md">
Real-time algorithmic trade ideas generated by <?php echo htmlspecialchars($siteName); ?> AI across crypto, equities, and forex. Confidence ratings reflect historical pattern success and multi-timeframe analysis.
</p>
</div>
<a href="/register" class="btn-get-started inline-flex items-center gap-2 px-6 py-3 rounded-lg font-bold text-label-sm shrink-0">
Unlock Full Feed <span class="material-symbols-outlined text-base">arrow_forward</span>
</a>
</div>
</div>
</section>

<section class="bg-[#F7F8FA] py-12 md:py-16 border-b border-gray-200">
<div class="max-w-[1440px] mx-auto px-4 md:px-margin-desktop">
<h2 class="font-headline-md text-headline-md text-surface-container-lowest mb-6">Cryptocurrency</h2>
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-gutter mb-10">
<?php foreach (get_markets_by_category('crypto') as $instrument): ?>
<?php require __DIR__ . '/includes/market-signal-card.php'; ?>
<?php endforeach; ?>
</div>

<h2 class="font-headline-md text-headline-md text-surface-container-lowest mb-6">Stocks</h2>
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-gutter mb-10">
<?php foreach (get_markets_by_category('stock') as $instrument): ?>
<?php require __DIR__ . '/includes/market-signal-card.php'; ?>
<?php endforeach; ?>
</div>

<h2 class="font-headline-md text-headline-md text-surface-container-lowest mb-6">Forex</h2>
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-gutter">
<?php foreach (get_markets_by_category('forex') as $instrument): ?>
<?php require __DIR__ . '/includes/market-signal-card.php'; ?>
<?php endforeach; ?>
</div>
</div>
</section>

<section class="py-16 md:py-20 bg-surface-container-lowest">
<div class="max-w-[1440px] mx-auto px-4 md:px-margin-desktop">
<div class="bg-surface-container-high border border-border-low rounded-2xl p-8 md:p-10 flex flex-col md:flex-row items-center justify-between gap-8">
<div>
<h2 class="font-display text-2xl md:text-3xl text-on-surface mb-3">Upgrade to <?php echo htmlspecialchars($siteName); ?> Premium</h2>
<p class="text-on-secondary-container max-w-xl">Get exclusive high-confidence signals, whale alerts, and AI portfolio coaching — built for serious investors.</p>
</div>
<div class="flex flex-col sm:flex-row gap-4 w-full md:w-auto shrink-0">
<a href="/register" class="btn-get-started text-center px-8 py-3 rounded-xl font-bold text-label-sm">Unlock Premium Feed</a>
<a href="/about_us" class="border border-outline text-on-surface px-8 py-3 rounded-xl font-bold text-label-sm text-center hover:bg-surface-container-high transition-colors">About Us</a>
</div>
</div>
<p class="text-on-secondary-container text-xs mt-6 max-w-3xl leading-relaxed">
Signals are for educational purposes only. Past performance does not guarantee future results. All trading involves risk.
</p>
</div>
</section>

<?php require_once __DIR__ . '/includes/marketing-footer.php'; ?>

<script src="/js/crypto-config.js"></script>
<script src="/js/crypto-prices.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  if (window.BloombitCryptoPrices) {
    var coins = <?php echo json_encode($cryptoIds); ?>;
    window.BloombitCryptoPrices.init(coins, { refreshInterval: 120000 });
    var cfg = window.BloombitCryptoConfig || {};
    document.querySelectorAll('.market-signal-card .crypto-logo').forEach(function(img) {
      var card = img.closest('.market-signal-card');
      var priceEl = card && card.querySelector('[data-coin]');
      var coinId = priceEl && priceEl.getAttribute('data-coin');
      if (!coinId) return;
      var logo = cfg.getLogo ? cfg.getLogo(coinId) : '';
      if (logo) { img.src = logo; img.alt = coinId; }
    });
  }
});
</script>
</body>
</html>
